name = "Chat Heads"
filename = "../chat_heads-0.3.1+1.17.1.jar"
side = "client"

[download]
url = "https://edge.forgecdn.net/files/3487/944/chat_heads-0.3.1+1.17.1.jar"
hash-format = "murmur2"
hash = "2619791207"

[update]
[update.curseforge]
file-id = 3487944
project-id = 407206
