name = "Drippy Loading Screen [Fabric]"
filename = "../drippyloadingscreen_fabric_1.1.1_MC_1.17-1.17.1.jar"
side = "client"

[download]
url = "https://edge.forgecdn.net/files/3452/210/drippyloadingscreen_fabric_1.1.1_MC_1.17-1.17.1.jar"
hash-format = "murmur2"
hash = "56383937"

[update]
[update.curseforge]
file-id = 3452210
project-id = 515172
release-channel = "beta"
