name = "Enhanced Block Entities"
filename = "../enhancedblockentities-0.4.1+1.17.jar"
side = "client"

[download]
url = "https://edge.forgecdn.net/files/3380/851/enhancedblockentities-0.4.1+1.17.jar"
hash-format = "murmur2"
hash = "793447886"

[update]
[update.curseforge]
file-id = 3380851
project-id = 452046
release-channel = "beta"
