name = "FancyMenu [Fabric]"
filename = "../fancymenu_fabric_2.3.3_MC_1.17-1.17.1.jar"
side = "client"

[download]
url = "https://edge.forgecdn.net/files/3475/0/fancymenu_fabric_2.3.3_MC_1.17-1.17.1.jar"
hash-format = "murmur2"
hash = "3362789279"

[update]
[update.curseforge]
file-id = 3475000
project-id = 416796
release-channel = "beta"
