name = "Inventory Profiles Next"
filename = "../InventoryProfilesNext-fabric-1.17-1.1.1.jar"
side = "client"

[download]
url = "https://edge.forgecdn.net/files/3493/796/InventoryProfilesNext-fabric-1.17-1.1.1.jar"
hash-format = "murmur2"
hash = "1417010311"

[update]
[update.curseforge]
file-id = 3493796
project-id = 495267
release-channel = "beta"
