name = "Inventory Profiles Next"
filename = "../InventoryProfilesNext-fabric-1.17-1.1.0.jar"
side = "client"

[download]
url = "https://edge.forgecdn.net/files/3490/628/InventoryProfilesNext-fabric-1.17-1.1.0.jar"
hash-format = "murmur2"
hash = "1562347470"

[update]
[update.curseforge]
file-id = 3490628
project-id = 495267
release-channel = "beta"
