name = "Mod Menu"
filename = "../modmenu-2.0.11.jar"
side = "client"

[download]
url = "https://cdn.modrinth.com//data/mOgUt4GM/versions/2.0.11/modmenu-2.0.11.jar"
hash-format = "sha512"
hash = "f7ff368917b4c4d6b5655de2a46584cba09e95c80cd6c70f1cd61589f999e2872be26ff3820b038dbf1b27fa79c09928b27fa492ff3d416daf536745121e2a6d"

[update]
[update.modrinth]
mod-id = "mOgUt4GM"
version = "FMqdptUn"
