name = "Mod Menu"
filename = "../modmenu-2.0.9.jar"
side = "client"

[download]
url = "https://cdn.modrinth.com//data/mOgUt4GM/versions/2.0.9/modmenu-2.0.9.jar"
hash-format = "sha512"
hash = "775905aaac1f7737e1747188792359cab577d4fb0fb30095430eb96e3c453403f18fc18e8f2e172a0fc2eb67b2149adf346b95e91953afe11fafbabd320ca740"

[update]
[update.modrinth]
mod-id = "mOgUt4GM"
version = "tlM0eBmY"
