name = "Physics Mod"
filename = "../physics-mod-2.5.10-mc-1.17.1.jar"
side = "client"

[download]
url = "https://edge.forgecdn.net/files/3465/999/physics-mod-2.5.10-mc-1.17.1.jar"
hash-format = "murmur2"
hash = "3214918972"

[update]
[update.curseforge]
file-id = 3465999
project-id = 442735
release-channel = "beta"
