name = "Skin Layers 3D"
filename = "../3dSkinLayers-1.0.1.jar"
side = "client"

[download]
url = "https://edge.forgecdn.net/files/3442/893/3dSkinLayers-1.0.1.jar"
hash-format = "murmur2"
hash = "402134832"

[update]
[update.curseforge]
file-id = 3442893
project-id = 521480
release-channel = "beta"
