name = "Window Title Changer"
filename = "../window_title_changer-2.1.1-1.17.jar"
side = "client"

[download]
url = "https://edge.forgecdn.net/files/3383/7/window_title_changer-2.1.1-1.17.jar"
hash-format = "murmur2"
hash = "508043363"

[update]
[update.curseforge]
file-id = 3383007
project-id = 359527
release-channel = "beta"
