name = "Xaero's World Map"
filename = "../XaerosWorldMap_1.16.1_Fabric_1.17.1.jar"
side = "client"

[download]
url = "https://edge.forgecdn.net/files/3423/299/XaerosWorldMap_1.16.1_Fabric_1.17.1.jar"
hash-format = "murmur2"
hash = "3120196149"

[update]
[update.curseforge]
file-id = 3423299
project-id = 317780
release-channel = "beta"
