name = "Xaero's Minimap (Fair-play Edition)"
filename = "../Xaeros_Minimap_FP21.19.0_Fabric_1.17.1.jar"
side = "client"

[download]
url = "https://edge.forgecdn.net/files/3495/268/Xaeros_Minimap_FP21.19.0_Fabric_1.17.1.jar"
hash-format = "murmur2"
hash = "3416055526"

[update]
[update.curseforge]
file-id = 3495268
project-id = 263466
release-channel = "beta"
