name = "hercios-survival"
author = "hertz"
version = "0.1"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3ef69aac44a7c8478a3412a7f266cc9dc05b4ec7f1f6ff009a77f7f051df8eec"

[versions]
fabric = "0.11.6"
minecraft = "1.17.1"

[options]
acceptable-game-versions = "1.17"
