name = "hercios-survival"
author = "hertz"
version = "0.0.1"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9205d59714288fd43ab024e7be1b51fafb660a3f924779faa1c03032e939d331"

[versions]
fabric = "0.11.7"
minecraft = "1.17.1"

[options]
acceptable-game-versions = "1.17"
