name = "hercios-survival"
author = "hertz"
version = "0.1"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f3e93a639150f58736b686b074321c38e99b7572400fa5448e387c66520694aa"

[versions]
fabric = "0.11.6"
minecraft = "1.17.1"

[options]
acceptable-game-versions = "1.17"
