name = "hercios-survival"
author = "hertz"
version = "0.0.1"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "393a0815578a52c9c3164154f0fe3709b27df61acfa3e00b1edecfe8c088dc57"

[versions]
fabric = "0.11.6"
minecraft = "1.17.1"

[options]
acceptable-game-versions = "1.17"
