name = "hercios-survival"
author = "hertz"
version = "0.0.1"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "64ae22820f335ce33dea730bae7ba9b630699f3546acff54054ab67dee5d2adf"

[versions]
fabric = "0.11.6"
minecraft = "1.17.1"

[options]
acceptable-game-versions = "1.17"
