name = "hercios-survival"
author = "hertz"
version = "0.1"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ca7fbf837ede5063461d38b94dd2022c7c3d637f22d3f992cc560ae81a3e5895"

[versions]
fabric = "0.11.6"
minecraft = "1.17.1"
