name = "hercios-survival"
author = "hertz"
version = "0.1"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ca62b7826ae3506c1c29ad167e46df9078c4fbf74d0c71e5f8a042de8bf56b46"

[versions]
fabric = "0.11.6"
minecraft = "1.17.1"

[options]
acceptable-game-versions = "1.17"
