name = "hercios-modpack"
author = "hertz"
version = "1.0"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "89064a356610b35fb60d96093e1092f02ab478c864f875d65430bebddfaec546"

[versions]
fabric = "0.11.7"
minecraft = "1.17.1"

[options]
acceptable-game-versions = ["1.17", "1.17.1"]
