name = "hercios-survival"
author = "hertz"
version = "0.0.1"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4ac84c99165c26d8dc440c44f6152deac9c246cf41d1f3736547a7ffc30c6cc9"

[versions]
fabric = "0.11.7"
minecraft = "1.17.1"

[options]
acceptable-game-versions = "1.17"
