name = "hercios-survival"
author = "hertz"
version = "0.0.1"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "22a899b6eb6f70388e8908e240c2d5776d838d1918976f2532c02d52e3d7fb6e"

[versions]
fabric = "0.11.6"
minecraft = "1.17.1"

[options]
acceptable-game-versions = "1.17"
