
#General Config Section
[general]
	#The Client ID of the Discord App to use
	clientID = 882035439274438686
	#Enable/Disable the mod
	enabled = true
	#Enable/Disable debugging mode. WARNING: MAY CAUSE LOG SPAM!
	debugging = false
	#Enable/Disable the in game config screen
	configScreen = true
	#Display the Icon and Pack Name in place of LargeImage from compatible launchers. DOES NOT WORK WITH CUSTOM APPS! ONLY THE DEFAULT ONE!
	launcherIntegration = false
	#Enable/Disabled in-game notifications about new releases
	updater = false
	#Internal Version Number. NO TOUCHY!
	version = 10

#The Game Loading event
[init]
	#Enable/Disable the Game Loading Event
	enabled = true
	#The first line of text under the app name
	description = "Minecraft esta cargando"
	#The second line of text under the app name
	state = "El juego comienza..."
	#The Asset ID of the image to display as the large image
	largeImageKey = "mc_logo"
	#The text that gets displayed when the large image is hovered
	largeImageText = "Minecraft %mcver%, pero con mods"
	#The Asset ID of the image to display as the small image
	smallImageKey = "mc_logo"
	#The text that gets displayed when the small image is hovered
	smallImageText = "%mods% mods"
	#The buttons to display on Discord
	buttons = []

#The Main Menu event
[main_menu]
	#Enable/Disable the Main Menu Event
	enabled = true
	#The first line of text under the app name
	description = "%player% se encuentra en el menu"
	#The seconds line of text under the app name
	state = "Chilling"
	#The Asset ID of the image to display as the large image
	largeImageKey = "mc_logo"
	#The text that gets displayed when the large image is hovered
	largeImageText = "Minecraft %mcver%, pero con mods"
	#The Asset ID of the image to display as the small image
	smallImageKey = "mc_logo"
	#The text that gets displayed when the small image is hovered
	smallImageText = "%mods% mods"
	#The buttons to display on Discord
	buttons = []

#The Server List event
[server_list]
	#Enable/Disable the Server List Event
	enabled = true
	#The first line of text under the app name
	description = "%player% se encuentra en el menu"
	#The second line of text under the app name
	state = "Chilling"
	#The Asset ID of the image to display as the large image
	largeImageKey = "mc_logo"
	#The text that gets displayed when the large image is hovered
	largeImageText = "Minecraft %mcver%, pero con mods"
	#The Asset ID of the image to display as the small image
	smallImageKey = "mc_logo"
	#The text that gets displayed when the small image is hovered
	smallImageText = "%mods% mods"
	#The buttons to display on Discord
	buttons = []

#The Join Game Event
[join_game]
	#Enable/Disable the Join Game Event
	enabled = false
	#The first line of text under the app name
	description = "%player% is joining a game"
	#The second line of text under the app name
	state = "Joining Game"
	#The Asset ID of the image to display as the large image
	largeImageKey = "mc_logo"
	#The text that gets displayed when the large image is hovered
	largeImageText = "Minecraft %mcver%, pero con mods"
	#The Asset ID of the image to display as the small image
	smallImageKey = "mc_logo"
	#The text that gets displayed when the small image is hovered
	smallImageText = "%mods% mods"
	#The buttons to display on Discord
	buttons = []

#The Single Player Event
[single_player]
	#Enable/Disable the Single Player Event
	enabled = true
	#The first line of text under the app name
	description = "En %world%"
	#The second line of text under the app name
	state = "Jugando en singleplayer"
	#The Asset ID of the image to display as the large image
	largeImageKey = "mc_logo"
	#The text that gets displayed when the large image is hovered
	largeImageText = "Minecraft %mcver%, pero con mods"
	#The Asset ID of the image to display as the small image
	smallImageKey = "mc_logo"
	#The text that gets displayed when the small image is hovered
	smallImageText = "%mods% mods"
	#The buttons to display on Discord
	buttons = []

#The Multi Player Event
[multi_player]
	#Enable/Disable the Multi Player Event
	enabled = true
	#The first line of text under the app name
	description = "Jugando en %servername% con %players% personas"
	#The second line of text under the app name
	state = "Jugando online"
	#The Asset ID of the image to display as the large image
	largeImageKey = "mc_logo"
	#The text that gets displayed when the large image is hovered
	largeImageText = "Minecraft %mcver%, pero con mods"
	#The Asset ID of the image to display as the small image
	smallImageKey = "mc_logo"
	#The text that gets displayed when the small image is hovered
	smallImageText = "%mods% mods"
	#The buttons to display on Discord
	buttons = []

#Fallback event for disabled events
[generic]
	#The first line of text under the app name
	description = "Jugando Minecraft"
	#The second line of text under the app name
	state = ""
	#The Asset ID of the image to display as the large image
	largeImageKey = "mc_logo"
	#The text that gets displayed when the large image is hovered
	largeImageText = "Minecraft %mcver%, pero con mods"
	#The Asset ID of the image to display as the small image
	smallImageKey = "mc_logo"
	#The text that gets displayed when the small image is hovered
	smallImageText = "%mods% mods"
	#The buttons to display on Discord
	buttons = []

#Dimension Information Overrides
[dimension_overrides]
	#Allows you to override the displayed values for dimensions
	enabled = false

	#The Dimensions to override
	[[dimension_overrides.dimensions]]
		name = "overworld"
		description = "%player% is in The Overworld"
		state = ""
		largeImageKey = "overworld"
		largeImageText = "In the Overworld"
		smallImageKey = "mc_logo"
		smallImageText = "%mods% mods"

	[[dimension_overrides.dimensions]]
		name = "the_nether"
		description = "%player% is in The Nether"
		state = ""
		largeImageKey = "nether"
		largeImageText = "In the Nether"
		smallImageKey = "mc_logo"
		smallImageText = "%mods% mods"

	[[dimension_overrides.dimensions]]
		name = "the_end"
		description = "%player% is in The End"
		state = ""
		largeImageKey = "end"
		largeImageText = "In the End"
		smallImageKey = "mc_logo"
		smallImageText = "%mods% mods"

