[general]
	clientID = 882035439274438686
	enabled = true
	debugging = false
	configScreen = false
	launcherIntegration = false
	updater = false
	version = 10

[init]
	enabled = false
	description = ""
	state = "El juego comienza..."
	largeImageKey = "modslogo"
	largeImageText = "Minecraft %mcver%, pero con mods"
	smallImageKey = "modslogo"
	smallImageText = "%mods% mods"
	buttons = []

[main_menu]
	enabled = false
	description = "%player% se encuentra en el menu"
	state = "Chilling"
	largeImageKey = "modslogo"
	largeImageText = "Minecraft %mcver%, pero con mods"
	smallImageKey = "modslogo"
	smallImageText = "%mods% mods"
	buttons = []

[server_list]
	enabled = false
	description = "%player% se encuentra en el menu"
	state = "Chilling"
	largeImageKey = "modslogo"
	largeImageText = "Minecraft %mcver%, pero con mods"
	smallImageKey = "modslogo"
	smallImageText = "%mods% mods"
	buttons = []

[join_game]
	enabled = false
	description = "%player% is joining a game"
	state = "Joining Game"
	largeImageKey = "modslogo"
	largeImageText = "Minecraft %mcver%, pero con mods"
	smallImageKey = "modslogo"
	smallImageText = "%mods% mods"
	buttons = []

[single_player]
	enabled = false
	description = "En %world%"
	state = "Jugando en singleplayer"
	largeImageKey = "modslogo"
	largeImageText = "Minecraft %mcver%, pero con mods"
	smallImageKey = "modslogo"
	smallImageText = "%mods% mods"
	buttons = []

[multi_player]
	enabled = true
	description = "En el servidor oficial"
	state = "con %players% jugadores"
	largeImageKey = "modslogo"
	largeImageText = "Minecraft %mcver%, pero con mods"
	smallImageKey = "mc_small"
	smallImageText = "%mods% mods"
	buttons = []

[generic]
	description = "En el menú"
	state = ""
	largeImageKey = "modslogo"
	largeImageText = "Minecraft %mcver%, pero con mods"
	smallImageKey = "mc_small"
	smallImageText = "%mods% mods"
	buttons = []

[dimension_overrides]
	enabled = false

	[[dimension_overrides.dimensions]]
		name = "overworld"
		description = "%player% is in The Overworld"
		state = ""
		largeImageKey = "overworld"
		largeImageText = "In the Overworld"
		smallImageKey = "modslogo"
		smallImageText = "%mods% mods"

	[[dimension_overrides.dimensions]]
		name = "the_nether"
		description = "%player% is in The Nether"
		state = ""
		largeImageKey = "nether"
		largeImageText = "In the Nether"
		smallImageKey = "modslogo"
		smallImageText = "%mods% mods"

	[[dimension_overrides.dimensions]]
		name = "the_end"
		description = "%player% is in The End"
		state = ""
		largeImageKey = "end"
		largeImageText = "In the End"
		smallImageKey = "modslogo"
		smallImageText = "%mods% mods"


