name = "Box of Placeholders"
filename = "../box-of-placeholders-1.3.3+1.17.1.jar"
side = "server"

[download]
url = "https://cdn.modrinth.com//data/iA9GjB4v/versions/1.3.3/box-of-placeholders-1.3.3+1.17.1.jar"
hash-format = "sha512"
hash = "9dee4721c6f998183722578695144e3fc9d6088157a7ca48788ca916d5452aa36f25abca42da1582e6d65a2ba1b5ba62c0d836c379d3a03fa951614bceac3f1e"

[update]
[update.modrinth]
mod-id = "iA9GjB4v"
version = "oElA630K"
