name = "Carpet TCTC Addition"
filename = "../Carpet-TCTC-Addition-fabric-mc1.17-1.1.3+build.15.jar"
side = "server"

[download]
url = "https://cdn.modrinth.com/data/vbBQ6dVH/versions/Carpet-TCTC-Addition-fabric-mc1.17-1.1.3+build.15/Carpet-TCTC-Addition-fabric-mc1.17-1.1.3+build.15.jar"
hash-format = "sha512"
hash = "ecf5447f6414aef65ecdbf3a297363a97459a20f868d2ac2d4d735dc113da66987bf9e5bee171ae8e24582f80cc258690ff9cb39632311baddd65f56302dccea"

[update]
[update.modrinth]
mod-id = "vbBQ6dVH"
version = "mSSEqgTd"
