name = "Caves and Cliffs add-on for William Wythers' Overworld"
filename = "../CavesAndCliffsAddOnForWilliamWythersOverhauledOverworld-1.3.jar"
side = "server"

[download]
url = "https://edge.forgecdn.net/files/3431/627/CavesAndCliffsAddOnForWilliamWythersOverhauledOverworld-1.3.jar"
hash-format = "murmur2"
hash = "743162320"

[update]
[update.curseforge]
file-id = 3431627
project-id = 497450
release-channel = "beta"
