name = "DeepslateCutting Fabric"
filename = "../deepslatecutting-1.2.2.jar"
side = "server"

[download]
url = "https://cdn.modrinth.com/data/IiuFShHs/versions/DeepslateCutting 1.2.2/deepslatecutting-1.2.2.jar"
hash-format = "sha512"
hash = "fe50fd5d1910b83e1472dc8f1f5004f5c22947402fc5a937de238bf3eee154f314b96f80bfc0aab7ba29fa26270edb9c4c5e9f355ff14a6e77a37ba31bf4ec95"

[update]
[update.modrinth]
mod-id = "IiuFShHs"
version = "HJIVJ1OT"
