name = "Dynmap-Forge/Fabric"
filename = "../Dynmap-3.2.1-fabric-1.17.1.jar"
side = "server"

[download]
url = "https://edge.forgecdn.net/files/3482/768/Dynmap-3.2.1-fabric-1.17.1.jar"
hash-format = "murmur2"
hash = "1128443376"

[update]
[update.curseforge]
file-id = 3482768
project-id = 59433
release-channel = "beta"
