name = "Fabric Dispenser Cauldron"
filename = "../dispenser-cauldron-1.0.4.jar"
side = "server"

[download]
url = "https://edge.forgecdn.net/files/3477/439/dispenser-cauldron-1.0.4.jar"
hash-format = "murmur2"
hash = "957228334"

[update]
[update.curseforge]
file-id = 3477439
project-id = 532165
release-channel = "beta"
