name = "Fence Player Upper"
filename = "../fenceplayerupper-1.1.3+1.17.pre1.jar"
side = "server"

[download]
url = "https://edge.forgecdn.net/files/3329/907/fenceplayerupper-1.1.3+1.17.pre1.jar"
hash-format = "murmur2"
hash = "4250311207"

[update]
[update.curseforge]
file-id = 3329907
project-id = 405591
release-channel = "beta"
