name = "Hat command"
filename = "../hat-command-2.2.0.jar"
side = "server"

[download]
url = "https://edge.forgecdn.net/files/3490/678/hat-command-2.2.0.jar"
hash-format = "murmur2"
hash = "3771539775"

[update]
[update.curseforge]
file-id = 3490678
project-id = 533947
