name = "Hat command"
filename = "../hat-command-2.2.1.jar"
side = "server"

[download]
url = "https://edge.forgecdn.net/files/3491/645/hat-command-2.2.1.jar"
hash-format = "murmur2"
hash = "1681902420"

[update]
[update.curseforge]
file-id = 3491645
project-id = 533947
