name = "More Structures add-on for William Wythers' Overhauled Overworld"
filename = "../MoreStructuresForWilliamWythersOverhauledOverworld-1.1.jar"
side = "server"

[download]
url = "https://edge.forgecdn.net/files/3372/261/MoreStructuresForWilliamWythersOverhauledOverworld-1.1.jar"
hash-format = "murmur2"
hash = "603689324"

[update]
[update.curseforge]
file-id = 3372261
project-id = 490711
release-channel = "beta"
