name = "Primordial Shores add-on for William Wythers' Overhauled Overworld"
filename = "../Primordial Shores add-on for William Wythers Overhauled Overworld.jar"
side = "server"

[download]
url = "https://edge.forgecdn.net/files/3369/418/Primordial Shores add-on for William Wythers Overhauled Overworld.jar"
hash-format = "murmur2"
hash = "3633435696"

[update]
[update.curseforge]
file-id = 3369418
project-id = 499106
release-channel = "beta"
