name = "Repurposed Structures - Fabric"
filename = "../repurposed_structures_fabric-2.3.5+1.17.1.jar"
side = "server"

[download]
url = "https://cdn.modrinth.com/data/muf0XoRe/versions/2.3.5+1.17.1/repurposed_structures_fabric-2.3.5+1.17.1.jar"
hash-format = "sha512"
hash = "2229de545ab6be785c370bc9633fbabc4c26aba15ae52695b4a1d4110dfb9cfcde222bafa7890d2bc863c158705eb601166932aafb1d88d3b0d2c7da03e151e7"

[update]
[update.modrinth]
mod-id = "muf0XoRe"
version = "GL4KREuI"
