name = "Repurposed Structures - Fabric"
filename = "../repurposed_structures_fabric-2.4.1+1.17.1.jar"
side = "server"

[download]
url = "https://cdn.modrinth.com/data/muf0XoRe/versions/2.4.1+1.17.1/repurposed_structures_fabric-2.4.1+1.17.1.jar"
hash-format = "sha512"
hash = "f892d3c18f1c4915238a654c7e36f1d6e0c8ec7f89fb41b76f698849bcddfdb641989a2ab38eb99355ba39f0848568a18526571051c9ff7db2771ce2accefdfb"

[update]
[update.modrinth]
mod-id = "muf0XoRe"
version = "6n0YfMae"
