name = "Repurposed Structures - Fabric"
filename = "../repurposed_structures_fabric-2.3.3+1.17.1.jar"
side = "server"

[download]
url = "https://cdn.modrinth.com//data/muf0XoRe/versions/2.3.3+1.17.1/repurposed_structures_fabric-2.3.3+1.17.1.jar"
hash-format = "sha512"
hash = "1d41205cc4f6f9a2546b561a8a2bd2ff2547c67dc0ae5e458d2c2ccf5c9d6b49e6881927bf30f137733b5068812aa9a2c027787ea600cdf4c6ce064fd99aff3b"

[update]
[update.modrinth]
mod-id = "muf0XoRe"
version = "VkcvApwP"
