name = "Semblance"
filename = "../semblance-1.0.0.jar"
side = "server"

[download]
url = "https://cdn.modrinth.com/data/FFiEdqAn/versions/1.0.0/semblance-1.0.0.jar"
hash-format = "sha512"
hash = "a59580e7ef595fdc018e78b317fe90aa45fefa07c5e8dcff9d1099a8cf7be5c5afa73a6a00f2db17c7b2a330b26845cd4b9baa11bdb7386601ebb23efde7c43d"

[update]
[update.modrinth]
mod-id = "FFiEdqAn"
version = "1emRkxeS"
