name = "Server Chat History"
filename = "../chathistory-1.2.0.jar"
side = "server"

[download]
url = "https://edge.forgecdn.net/files/3478/261/chathistory-1.2.0.jar"
hash-format = "murmur2"
hash = "2010528651"

[update]
[update.curseforge]
file-id = 3478261
project-id = 531614
release-channel = "beta"
