name = "Server Chat History"
filename = "../chathistory-1.1.0.jar"
side = "server"

[download]
url = "https://edge.forgecdn.net/files/3476/865/chathistory-1.1.0.jar"
hash-format = "murmur2"
hash = "3717041892"

[update]
[update.curseforge]
file-id = 3476865
project-id = 531614
release-channel = "beta"
