name = "Server Chat History"
filename = "../chathistory-1.0.0.jar"
side = "server"

[download]
url = "https://edge.forgecdn.net/files/3475/225/chathistory-1.0.0.jar"
hash-format = "murmur2"
hash = "2294836063"

[update]
[update.curseforge]
file-id = 3475225
project-id = 531614
release-channel = "beta"
