name = "Sneak Nether Portals"
filename = "../sneaknetherportals-1.2.jar"
side = "server"

[download]
url = "https://edge.forgecdn.net/files/3358/560/sneaknetherportals-1.2.jar"
hash-format = "murmur2"
hash = "2982759237"

[update]
[update.curseforge]
file-id = 3358560
project-id = 461106
release-channel = "beta"
