name = "Styled Nicknames"
filename = "../styled-nicknames-1.0.1.jar"
side = "server"

[download]
url = "https://cdn.modrinth.com//data/DOk6Gcdi/versions/1.0.1/styled-nicknames-1.0.1.jar"
hash-format = "sha512"
hash = "335bc25177840bbf0488432a0970ef08c97b0e6201c4c10b3995679f6d339f13a948df8e64670ad5125108e20ed396ae891b03d277caa862edd67ce678f16110"

[update]
[update.modrinth]
mod-id = "DOk6Gcdi"
version = "cUpLgUQC"
