name = "Styled Player List"
filename = "../styledplayerlist-2.1.0.jar"
side = "server"

[download]
url = "https://cdn.modrinth.com/data/DQIfKUHf/versions/2.1.0/styledplayerlist-2.1.0.jar"
hash-format = "sha512"
hash = "44738bb89a94bef8049a91a406fe239de95c6033764648593a0b1e5f8657739202fb3b281f66d830f178ac07ad5b0db692a3f353b9882c3889f27e2574dbcccc"

[update]
[update.modrinth]
mod-id = "DQIfKUHf"
version = "IRzh45e3"
