name = "Styled Player List"
filename = "../styledplayerlist-2.1.2.jar"
side = "server"

[download]
url = "https://cdn.modrinth.com/data/DQIfKUHf/versions/2.1.2/styledplayerlist-2.1.2.jar"
hash-format = "sha512"
hash = "ce4216c8e861ebfc2fca2a6ab03e9acc159b68c416e964bcdb3a323d3cf02f6f51f221b32cf7b96b2a3b3c389aef8772ddcd605745840bafd69b895bd57bacbf"

[update]
[update.modrinth]
mod-id = "DQIfKUHf"
version = "eTkAj4IY"
