name = "William Wythers' Overhauled Overworld"
filename = "../WilliamWythersOverhauledOverworld-1.6(1.17.x).jar"
side = "server"

[download]
url = "https://edge.forgecdn.net/files/3431/640/WilliamWythersOverhauledOverworld-1.6(1.17.x).jar"
hash-format = "murmur2"
hash = "3759426575"

[update]
[update.curseforge]
file-id = 3431640
project-id = 490686
release-channel = "beta"
