name = "AdaPaxels"
filename = "adapaxels-1.2.1+1.17.1.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3402/776/adapaxels-1.2.1+1.17.1.jar"
hash-format = "murmur2"
hash = "327886118"

[update]
[update.curseforge]
file-id = 3402776
project-id = 406691
release-channel = "beta"
