name = "Beacon Overhaul"
filename = "BeaconOverhaul-1.4.1+1.17.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3380/414/BeaconOverhaul-1.4.1+1.17.jar"
hash-format = "murmur2"
hash = "2327747689"

[update]
[update.curseforge]
file-id = 3380414
project-id = 430382
release-channel = "beta"
