name = "BedrockIfy"
filename = "bedrockify-1.1.1+mc1.17.jar"
side = "both"

[download]
url = "https://cdn.modrinth.com/data/ox3rDp1B/versions/1.1.0+mc1.17/bedrockify-1.1.1+mc1.17.jar"
hash-format = "sha512"
hash = "f599da622b75b2f140aac13acf27aad7564f5e345577679d91a0633c2b27e0df1872ecc80db3ff99ae0a39d5e2f56cdacbde28b4fde4cf9f15c74f9ea4529335"

[update]
[update.modrinth]
mod-id = "ox3rDp1B"
version = "cylF2m0s"
