name = "BeehiveTooltips"
filename = "beehive-tooltips-1.3.0.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3375/603/beehive-tooltips-1.3.0.jar"
hash-format = "murmur2"
hash = "1790951767"

[update]
[update.curseforge]
file-id = 3375603
project-id = 376753
release-channel = "beta"
