name = "Better Signs & Frames"
filename = "better-signs-and-frames-0.8.2.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3395/533/better-signs-and-frames-0.8.2.jar"
hash-format = "murmur2"
hash = "3232236414"

[update]
[update.curseforge]
file-id = 3395533
project-id = 384963
release-channel = "beta"
