name = "Centered inventory"
filename = "centeredinventory-1.0.3.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3353/454/centeredinventory-1.0.3.jar"
hash-format = "murmur2"
hash = "3445906742"

[update]
[update.curseforge]
file-id = 3353454
project-id = 492588
release-channel = "beta"
