name = "Chat Up!"
filename = "chat-up-2.0.0.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3345/782/chat-up-2.0.0.jar"
hash-format = "murmur2"
hash = "4201575283"

[update]
[update.curseforge]
file-id = 3345782
project-id = 367561
release-channel = "beta"
