name = "CraftingPad (Fabric)"
filename = "craftingpad-1.17.1-fabric0.36.1-1.0.5.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3379/969/craftingpad-1.17.1-fabric0.36.1-1.0.5.jar"
hash-format = "murmur2"
hash = "1616630893"

[update]
[update.curseforge]
file-id = 3379969
project-id = 308976
release-channel = "beta"
