name = "Decorative"
filename = "decorative-4.1.1.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3345/338/decorative-4.1.1.jar"
hash-format = "murmur2"
hash = "2366672732"

[update]
[update.curseforge]
file-id = 3345338
project-id = 394007
release-channel = "beta"
