name = "Enhanced Celestials(Fabric) - Blood Moons & Harvest Moons"
filename = "enhancedcelestials-2.0.3.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3438/558/enhancedcelestials-2.0.3.jar"
hash-format = "murmur2"
hash = "1185246876"

[update]
[update.curseforge]
file-id = 3438558
project-id = 443694
release-channel = "beta"
