name = "Mo'Enchantments"
filename = "MoEnchantments-1.18.0.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3442/367/MoEnchantments-1.18.0.jar"
hash-format = "murmur2"
hash = "1256528106"

[update]
[update.curseforge]
file-id = 3442367
project-id = 320806
release-channel = "beta"
