name = "FancyMenu [Fabric]"
filename = "fancymenu_fabric_2.2.2-2_MC_1.17-1.17.1.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3436/992/fancymenu_fabric_2.2.2-2_MC_1.17-1.17.1.jar"
hash-format = "murmur2"
hash = "2816518396"

[update]
[update.curseforge]
file-id = 3436992
project-id = 416796
release-channel = "beta"
