name = "Wildfire's Female Gender Mod (Fabric)"
filename = "%5BFabric%5D Wildfire Female Gender Mod-2.6.1.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3345/985/%5BFabric%5D Wildfire Female Gender Mod-2.6.1.jar"
hash-format = "murmur2"
hash = "1733650390"

[update]
[update.curseforge]
file-id = 3345985
project-id = 456319
release-channel = "beta"
