name = "Food Enhancements"
filename = "fabric-food_enhancements-1.5.1.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3442/315/fabric-food_enhancements-1.5.1.jar"
hash-format = "murmur2"
hash = "238564766"

[update]
[update.curseforge]
file-id = 3442315
project-id = 430471
release-channel = "beta"
