name = "GeckoLib"
filename = "geckolib-fabric-1.17-3.0.13.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3428/829/geckolib-fabric-1.17-3.0.13.jar"
hash-format = "murmur2"
hash = "2998133121"

[update]
[update.curseforge]
file-id = 3428829
project-id = 388172
release-channel = "beta"
