name = "Keybind Search"
filename = "keybind-search-1.17-1.0.0.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3329/322/keybind-search-1.17-1.0.0.jar"
hash-format = "murmur2"
hash = "499816414"

[update]
[update.curseforge]
file-id = 3329322
project-id = 420154
release-channel = "beta"
