name = "Konkrete [Fabric]"
filename = "konkrete_fabric_1.2.3_MC_1.17-1.17.1.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3405/590/konkrete_fabric_1.2.3_MC_1.17-1.17.1.jar"
hash-format = "murmur2"
hash = "2218793539"

[update]
[update.curseforge]
file-id = 3405590
project-id = 416797
release-channel = "beta"
