name = "Magick: Potions and Pearls"
filename = "magick-1.0.5.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3412/563/magick-1.0.5.jar"
hash-format = "murmur2"
hash = "3148449684"

[update]
[update.curseforge]
file-id = 3412563
project-id = 497340
release-channel = "beta"
