name = "More Respawn Anchors"
filename = "morerespawnanchors-1.0.2.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3424/741/morerespawnanchors-1.0.2.jar"
hash-format = "murmur2"
hash = "3613990758"

[update]
[update.curseforge]
file-id = 3424741
project-id = 442640
release-channel = "beta"
