name = "Near-Sightedly"
filename = "nearsightedly-1.2.1.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3439/155/nearsightedly-1.2.1.jar"
hash-format = "murmur2"
hash = "2596782205"

[update]
[update.curseforge]
file-id = 3439155
project-id = 514002
release-channel = "beta"
