name = "Things"
filename = "things-0.2.5.jar"
side = "both"

[download]
url = "https://cdn.modrinth.com/data/VzAGdu9D/versions/0.2.5/things-0.2.5.jar"
hash-format = "sha512"
hash = "e4556aaa9ed2b8f8eed25d36d041214d825fd81bffa87b3bfca3d9b017a3badab75e675a4cb2478dad8eb78893012e52486817a0116b4499bbd2ae9d07ecb2e4"

[update]
[update.modrinth]
mod-id = "VzAGdu9D"
version = "sM3q1HIY"
