name = "Why Am I on Fire?"
filename = "whyamionfire-1.1.1.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3351/545/whyamionfire-1.1.1.jar"
hash-format = "murmur2"
hash = "2012672294"

[update]
[update.curseforge]
file-id = 3351545
project-id = 470990
release-channel = "beta"
