name = "Item Counts (Fabric)"
filename = "../../itemcounts-1.0.0+mc1.17.1.jar"
side = "client"

[download]
url = "https://edge.forgecdn.net/files/3457/78/itemcounts-1.0.0+mc1.17.1.jar"
hash-format = "murmur2"
hash = "3087487546"

[update]
[update.curseforge]
file-id = 3457078
project-id = 526663
release-channel = "beta"

[option]
optional = true
description = "Este mod muestra la cantidad total de cada item en el inventario."