name = "Adorn"
filename = "../Adorn-2.1.5+1.17.1-fabric.jar"
side = "both"

[download]
url = "https://cdn.modrinth.com//data/E6FUtRJh/versions/2.1.5/Adorn-2.1.5+1.17.1-fabric.jar"
hash-format = "sha512"
hash = "43d819c7347c0a5d5b7f6064eabd5860bf25448ef2f892339800d10c82965dbed45f9f6cee6a3ad8935192914fa40d45532dc69e957cdcf23073a1c77dbfaddb"

[update]
[update.modrinth]
mod-id = "E6FUtRJh"
version = "PMcVhh7K"
