name = "Architect's Palette [FABRIC]"
filename = "../architects-palette-fabric-port-1.2.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3358/890/architects-palette-fabric-port-1.2.jar"
hash-format = "murmur2"
hash = "3669670885"

[update]
[update.curseforge]
file-id = 3358890
project-id = 487364
release-channel = "beta"
