name = "Art of Alchemy - Continued"
filename = "../artofalchemy-1.3.0+1.17.1.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3474/840/artofalchemy-1.3.0+1.17.1.jar"
hash-format = "murmur2"
hash = "3000150059"

[update]
[update.curseforge]
file-id = 3474840
project-id = 531799
release-channel = "beta"
