name = "Art of Alchemy - Continued"
filename = "../artofalchemy-1.3.1+1.17.1.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3477/243/artofalchemy-1.3.1+1.17.1.jar"
hash-format = "murmur2"
hash = "1542667583"

[update]
[update.curseforge]
file-id = 3477243
project-id = 531799
release-channel = "beta"
