name = "Art of Alchemy - Continued"
filename = "../artofalchemy-1.3.2+1.17.1.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3478/82/artofalchemy-1.3.2+1.17.1.jar"
hash-format = "murmur2"
hash = "720640363"

[update]
[update.curseforge]
file-id = 3478082
project-id = 531799
release-channel = "beta"
