name = "Blockus"
filename = "../blockus-2.2.9+1.17.1.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3464/345/blockus-2.2.9+1.17.1.jar"
hash-format = "murmur2"
hash = "3860295291"

[update]
[update.curseforge]
file-id = 3464345
project-id = 312289
release-channel = "beta"
