name = "Bounding Box Outline Reloaded"
filename = "../BBOutlineReloaded-2.4-1.17.1-fabric-beta2.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3426/411/BBOutlineReloaded-2.4-1.17.1-fabric-beta2.jar"
hash-format = "murmur2"
hash = "3407944735"

[update]
[update.curseforge]
file-id = 3426411
project-id = 272578
release-channel = "beta"