name = "Conjuring"
filename = "../conjuring-1.0.9.jar"
side = "both"

[download]
url = "https://cdn.modrinth.com/data/GriMtaoD/versions/1.0.9/conjuring-1.0.9.jar"
hash-format = "sha512"
hash = "10f6c657f186f2dd2f2202fe2cf357c5cd1529872b74fd3b18594a5833e53d76afd6cba18b3f0767a18d21bd507b8bc3a59b20bb75cfa656bd16758f17d90431"

[update]
[update.modrinth]
mod-id = "GriMtaoD"
version = "5lyfF52O"
