name = "Conjuring [Fabric/Forge]"
filename = "../conjuring-1.0.11.jar"
side = "both"

[download]
url = "https://media.forgecdn.net/files/3489/321/conjuring-1.0.11.jar"
hash-format = "murmur2"
hash = "79252605"

[update]
[update.curseforge]
file-id = 3489321
project-id = 422310
