name = "Data Attributes"
filename = "../dataattributes-1.0.3-1.17.1.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3459/916/dataattributes-1.0.3-1.17.1.jar"
hash-format = "murmur2"
hash = "958347593"

[update]
[update.curseforge]
file-id = 3459916
project-id = 514734
release-channel = "beta"