name = "Data Attributes"
filename = "../dataattributes-1.0.4-1.17.1.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3462/727/dataattributes-1.0.4-1.17.1.jar"
hash-format = "murmur2"
hash = "553069129"

[update]
[update.curseforge]
file-id = 3462727
project-id = 514734
release-channel = "beta"
