name = "Draylar's Battle Towers"
filename = "../battletowers-3.4.0-1.17.1.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3456/996/battletowers-3.4.0-1.17.1.jar"
hash-format = "murmur2"
hash = "3160563034"

[update]
[update.curseforge]
file-id = 3456996
project-id = 315386
release-channel = "beta"
