name = "Eldritch Mobs"
filename = "../eldritch-mobs-1.9.2.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3425/438/eldritch-mobs-1.9.2.jar"
hash-format = "murmur2"
hash = "4028674647"

[update]
[update.curseforge]
file-id = 3425438
project-id = 392015
release-channel = "beta"
