name = "Emotecraft (Fabric)"
filename = "../emotecraft-for-MC1.17.1-2.1-SNAPSHOT-build.4-fabric.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3443/110/emotecraft-for-MC1.17.1-2.1-SNAPSHOT-build.4-fabric.jar"
hash-format = "murmur2"
hash = "1978639236"

[update]
[update.curseforge]
file-id = 3443110
project-id = 397809
release-channel = "beta"
