name = "Emotecraft (Fabric)"
filename = "../emotecraft-for-MC1.17.1-2.1-SNAPSHOT-build.6-fabric.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3458/653/emotecraft-for-MC1.17.1-2.1-SNAPSHOT-build.6-fabric.jar"
hash-format = "murmur2"
hash = "3007097854"

[update]
[update.curseforge]
file-id = 3458653
project-id = 397809
release-channel = "beta"
