name = "Emotecraft (Fabric)"
filename = "../emotecraft-for-MC1.17.1-2.1-SNAPSHOT-build.5-fabric.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3456/235/emotecraft-for-MC1.17.1-2.1-SNAPSHOT-build.5-fabric.jar"
hash-format = "murmur2"
hash = "2388464203"

[update]
[update.curseforge]
file-id = 3456235
project-id = 397809
release-channel = "beta"
