name = "Fabrication"
filename = "../fabrication-1.17-2.0.0-pre4.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3426/957/fabrication-1.17-2.0.0-pre4.jar"
hash-format = "murmur2"
hash = "2621174125"

[update]
[update.curseforge]
file-id = 3426957
project-id = 414445
release-channel = "beta"
