name = "Gobber [FABRIC]"
filename = "../Gobber2-Fabric-1.17.1-2.4.51.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3478/589/Gobber2-Fabric-1.17.1-2.4.51.jar"
hash-format = "murmur2"
hash = "1663116006"

[update]
[update.curseforge]
file-id = 3478589
project-id = 427177
release-channel = "beta"
