name = "Gobber [FABRIC]"
filename = "Gobber2-Fabric-1.17.1-2.4.42.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3446/648/Gobber2-Fabric-1.17.1-2.4.42.jar"
hash-format = "murmur2"
hash = "775573466"

[update]
[update.curseforge]
file-id = 3446648
project-id = 427177
release-channel = "beta"
