name = "Gobber [FABRIC]"
filename = "../Gobber2-Fabric-1.17.1-2.4.50.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3476/942/Gobber2-Fabric-1.17.1-2.4.50.jar"
hash-format = "murmur2"
hash = "1145868475"

[update]
[update.curseforge]
file-id = 3476942
project-id = 427177
release-channel = "beta"
