name = "Gobber [FABRIC]"
filename = "../Gobber2-Fabric-1.17.1-2.4.44.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3452/118/Gobber2-Fabric-1.17.1-2.4.44.jar"
hash-format = "murmur2"
hash = "447931042"

[update]
[update.curseforge]
file-id = 3452118
project-id = 427177
release-channel = "beta"
