name = "Grind Enchantments"
filename = "../grind-enchantments-1.3.0+1.17.1.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3451/397/grind-enchantments-1.3.0+1.17.1.jar"
hash-format = "murmur2"
hash = "3424099174"

[update]
[update.curseforge]
file-id = 3451397
project-id = 379680
release-channel = "beta"
