name = "Icarus (Fabric)"
filename = "../icarus-1.6.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3496/765/icarus-1.6.jar"
hash-format = "murmur2"
hash = "2350185681"

[update]
[update.curseforge]
file-id = 3496765
project-id = 428151
release-channel = "beta"
