name = "Kibe Utilities"
filename = "../kibe-1.9-BETA+1.17.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3467/233/kibe-1.9-BETA+1.17.jar"
hash-format = "murmur2"
hash = "831764712"

[update]
[update.curseforge]
file-id = 3467233
project-id = 388832
release-channel = "beta"
