name = "LevelZ"
filename = "../levelz-1.0.5.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3437/911/levelz-1.0.5.jar"
hash-format = "murmur2"
hash = "3520693838"

[update]
[update.curseforge]
file-id = 3437911
project-id = 517130
release-channel = "beta"
