name = "Magic Fungi"
filename = "../magicfungi-0.4.0-BETA+1.17.1.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3464/336/magicfungi-0.4.0-BETA+1.17.1.jar"
hash-format = "murmur2"
hash = "2904309162"

[update]
[update.curseforge]
file-id = 3464336
project-id = 506412
release-channel = "beta"
