name = "Magic Fungi"
filename = "../magicfungi-0.3.1-BETA+1.17.1.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3453/921/magicfungi-0.3.1-BETA+1.17.1.jar"
hash-format = "murmur2"
hash = "3072350455"

[update]
[update.curseforge]
file-id = 3453921
project-id = 506412
release-channel = "beta"