name = "More Gems [FABRIC]"
filename = "../MoreGems-Fabric-1.17.1-1.2.35.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3459/330/MoreGems-Fabric-1.17.1-1.2.35.jar"
hash-format = "murmur2"
hash = "2016995928"

[update]
[update.curseforge]
file-id = 3459330
project-id = 377284
release-channel = "beta"
