name = "More Gems [FABRIC]"
filename = "../MoreGems-Fabric-1.17.1-1.2.40.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3493/499/MoreGems-Fabric-1.17.1-1.2.40.jar"
hash-format = "murmur2"
hash = "2495354741"

[update]
[update.curseforge]
file-id = 3493499
project-id = 377284
release-channel = "beta"
