name = "More Totems Of Undying"
filename = "../more-totems-mod-2.8.0.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3372/733/more-totems-mod-2.8.0.jar"
hash-format = "murmur2"
hash = "2949719653"

[update]
[update.curseforge]
file-id = 3372733
project-id = 357265
release-channel = "beta"
