name = "More Gems [FABRIC]"
filename = "../MoreGems-Fabric-1.17.1-1.2.39.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3476/835/MoreGems-Fabric-1.17.1-1.2.39.jar"
hash-format = "murmur2"
hash = "311166456"

[update]
[update.curseforge]
file-id = 3476835
project-id = 377284
release-channel = "beta"
