name = "Nether Chest"
filename = "../netherchest-mc1.17.x-2.0.jar"
side = "both"

[download]
url = "https://cdn.modrinth.com/data/okOUGirG/versions/mc1.17.x-2.0/netherchest-mc1.17.x-2.0.jar"
hash-format = "sha512"
hash = "dfcf07b7343ad0c0c6482d34f48929afa8c9542e7313f26956bab47cfb51c2d29522c1302991e69d1df1bc5718ce1595de4f84ce199ce475c90e21e6586f6208"

[update]
[update.modrinth]
mod-id = "okOUGirG"
version = "Zkd3HZOH"
