name = "Not Enough Crashes (Fabric)"
filename = "../notenoughcrashes-3.6.4+1.17.1-fabric.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3475/869/notenoughcrashes-3.6.4+1.17.1-fabric.jar"
hash-format = "murmur2"
hash = "1685357637"

[update]
[update.curseforge]
file-id = 3475869
project-id = 353890
release-channel = "beta"
