name = "PlayerEx"
filename = "../playerex-3.0.4-1.17.1.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3466/875/playerex-3.0.4-1.17.1.jar"
hash-format = "murmur2"
hash = "2242234577"

[update]
[update.curseforge]
file-id = 3466875
project-id = 409221
release-channel = "beta"
