name = "Polymorph (Fabric)"
filename = "../polymorph-fabric-0.0.13-1.17.1.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3456/113/polymorph-fabric-0.0.13-1.17.1.jar"
hash-format = "murmur2"
hash = "3619375603"

[update]
[update.curseforge]
file-id = 3456113
project-id = 397434
release-channel = "beta"
