name = "Rhino"
filename = "../rhino-1605.1.2-build.47.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3427/364/rhino-1605.1.2-build.47.jar"
hash-format = "murmur2"
hash = "4086141203"