name = "ShieldBalancing"
filename = "../shieldbalancing-1.0.2.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3356/99/shieldbalancing-1.0.2.jar"
hash-format = "murmur2"
hash = "2707768904"

[update]
[update.curseforge]
file-id = 3356099
project-id = 463413
release-channel = "beta"
