name = "Simple Voice Chat"
filename = "../voicechat-fabric-1.17.1-1.1.11.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3457/230/voicechat-fabric-1.17.1-1.1.11.jar"
hash-format = "murmur2"
hash = "4216610059"

[update]
[update.curseforge]
file-id = 3457230
project-id = 416089
release-channel = "beta"
