name = "Simple Voice Chat"
filename = "../voicechat-fabric-1.17.1-2.1.3.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3495/4/voicechat-fabric-1.17.1-2.1.3.jar"
hash-format = "murmur2"
hash = "813101911"

[update]
[update.curseforge]
file-id = 3495004
project-id = 416089
release-channel = "beta"
