name = "Simple Voice Chat"
filename = "../voicechat-fabric-1.17.1-1.1.7.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3424/549/voicechat-fabric-1.17.1-1.1.7.jar"
hash-format = "murmur2"
hash = "4042783715"

[update]
[update.curseforge]
file-id = 3424549
project-id = 416089
release-channel = "beta"
