name = "The Graveyard (FABRIC)"
filename = "../The_Graveyard_1.2_(FABRIC)_for_1.17-1.17.1.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3431/619/The_Graveyard_1.2_(FABRIC)_for_1.17-1.17.1.jar"
hash-format = "murmur2"
hash = "1590397722"

[update]
[update.curseforge]
file-id = 3431619
project-id = 514468
release-channel = "beta"
