name = "VanillaTweaks (Fabric)"
filename = "../VanillaTweaks-1.17.1-1.0.17.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3482/58/VanillaTweaks-1.17.1-1.0.17.jar"
hash-format = "murmur2"
hash = "3402314789"

[update]
[update.curseforge]
file-id = 3482058
project-id = 428252
release-channel = "beta"
