name = "VanillaTweaks (Fabric)"
filename = "../VanillaTweaks-1.17.1-1.0.16.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3476/991/VanillaTweaks-1.17.1-1.0.16.jar"
hash-format = "murmur2"
hash = "3308268775"

[update]
[update.curseforge]
file-id = 3476991
project-id = 428252
release-channel = "beta"
