name = "WTHIT"
filename = "../wthit-fabric-3.9.0.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3453/929/wthit-fabric-3.9.0.jar"
hash-format = "murmur2"
hash = "916443355"

[update]
[update.curseforge]
file-id = 3453929
project-id = 440979
release-channel = "beta"
